POST http://localhost:4004/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Minhaz",
  "email": "zcxasxs@gmail.com",
  "address": "Khilgaon",
  "gender": "Male",
  "birthDate": "1997-07-21",
  "registrationDate": "2024-01-01"
}